server:
  port: 9199
  servlet:
    context-path: /registration-service
spring:
  application:
    name: keycloak-Test
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keycloak?autoreconnect=true
    username: root
    password: welcome
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

sso:
  server-url: http://localhost:8080
  username: admin
  password: admin
  realm: master
  client-id: admin-cli
  client-secret: 66tpSSB0LMO8OdEVRKSMvlWdRZq9VZW2
